#!/bin/bash

TMP_DIR="$BACKUP_TMP_DIR"

# don’t compress <256B files; 
# use bzip compression; 
# ignore *.dar files
DAR_OPTIONS='-m 256 -y -P *.dar'

# this will be passed directly to scp as a server, i.e. `scp xxx $SERVER:yyy`
SERVER="`whoami`@localhost"

