#!/bin/bash

# TODO: mysql module unit test

set -e

PATH="$PATH:`readlink -f ../src/bin`"; export PATH 

. "`backup-include mysql`"
if [[ -e 'tmp' ]]; then
    rm -r 'tmp'
fi
mkdir -p 'tmp'
pushd "$PWD"
cd 'tmp'
backup_mysql_full 'backup_test' 'root' '' "`ignore_table_opt backup_test 'table2 table3'`" '-tmp s.sql' '-keep s.tmp.sql'
backup_mysql_incr 'backup_test' 'root' '' "`ignore_table_opt backup_test 'table2 table3'`" '-keep s.tmp.sql' '-new s.tmp.sql' '-tmp s.sql.diff'
popd

# TODO: automated check & cleanup

