#!/bin/bash

# TODO: dar module unit test

set -e

PATH="$PATH:`readlink -f ../src/bin`"; export PATH 

. "`backup-include dar`"
if [[ -e 'tmp' ]]; then
    rm -r 'tmp'
fi
mkdir -p 'tmp/'{'-0 zero','-1 one','-2 two'}
pushd "$PWD"
cd 'tmp'

# library functions
backup_dar_full '../data/test.0' '-0 zero/-bak kab'
backup_dar_incr '../data/test.1' '-0 zero/-bak kab' '-1 one/-bak kab.inc'
backup_dar_incr '../data/test.2' '-1 one/-bak kab.inc' '-2 two/-bak kab.inc'

# automated mode
mkdir -p 'auto'
BACKUP_DIR=`readlink -f auto`; export BACKUP_DIR

BACKUP_DATE='-0 zero' 
. backup-init # has to be executed in current script's context
backup-dar '../data/test.0' -a '-aliaz zzz'

BACKUP_DATE='-1 one' 
. backup-init
backup-dar '../data/test.1' -a '-aliaz zzz' --incremental

BACKUP_DATE='-2 two'
. backup-init
backup-dar '../data/test.2' -a '-aliaz zzz' --incremental

# TODO: automated check & cleanup

popd

