#!/bin/bash


set -e

usage() {
    cat << EOF
usage: 
    ${0##*/} DIR DST DATE PREV_DATE

makes full backup of DIR to TMP_DIR/DATE/files/DST.1.dar 
or incremental backup of DIR against TMP_DIR/PREV_DATE/files/DST.1.dar
or TMP_DIR/PREV_DATE/files/DST.inc.1.dar to TMP_DIR/DATE/files/DST.inc.1.dar

TMP_DIR is set in ./backup-options

TMP_DIR/.last has the date of the last backup';' all
successive incremental backups will be performed against it

use "-" as PREV_DATE to make a full backup


Examples

full backup, note the "-" in PREV_DATE place:
    ${0##*/} /var/log var-log 2011-09-01 -

incremental backup against a full backup:
    ${0##*/} /var/log var-log 2011-09-02 2011-09-01
 
incremental backup against another incremental backup:
    ${0##*/} /var/log var-log 2011-09-03 2011-09-02
EOF
    exit 1
}

SRC=$1
DST=$2
DATE=$3
PREV_DATE=$4 # only for incremental backup

if [[ -z $SRC || -z $DST  || -z $DATE || -z $PREV_DATE ]]; then
    usage
fi

. ./backup-options

if [[ "$PREV_DATE" != "-" ]]; then
    IS_INCR=1
fi

mkdir -p $TMP_DIR/$DATE/files

BACKUP=$TMP_DIR/$DATE/files/$DST

if [[ ! $IS_INCR ]]; then
    # full backup
    dar $DAR_OPTIONS -R $SRC -c $BACKUP
else
    # incremental backup

    BACKUP=$BACKUP.inc

    INCR_SRC=$TMP_DIR/$PREV_DATE/files/$DST # against a full backup by default
    if [[ -e $INCR_SRC.inc.1.dar ]]; then # against an incremental backup
        INCR_SRC=$INCR_SRC.inc
    fi

    dar $DAR_OPTIONS -R $SRC -c $BACKUP -A $INCR_SRC
fi

