#!/bin/bash


set -e

usage() {
    cat << EOF
usage:
    ${0##*/} TYPE SRC SRV_ID DATE

copies TMP_DIR/DATE/TYPE/SRC to SERVER:/SRV_ID/DATE/TYPE/SRC over scp

Examples

full file backup:
    ${0##*/} files var-log.1.dar wmdemo 2011-09-02

incremental file backup:
    ${0##*/} files var-log.inc.1.dar wmdemo 2011-09-02

full db backup:
    ${0##*/} db kartawm.sql.bz2 wmdemo 2011-09-02

incremental db backup:
    ${0##*/} db kartawm.sql.diff.bz2 wmdemo 2011-09-02
EOF
    exit 1
}

TYPE=$1         # ‘files’ or ‘db’
SRC=$2          # var-log.1.dar, var-log.inc.1.dar, kartawm.sql.bz2, kartawm.sql.diff.bz2
SRV_ID=$3       # just to distinguish backups from different servers
DATE=$4         # 2011-01-19

if [[ -z $TYPE || -z $SRC || -z $SRV_ID || -z $DATE ]]; then
    usage
fi

. ./backup-options

FROM=$TMP_DIR/$DATE/$TYPE/$SRC
TO=$SRV_ID/$DATE/$TYPE/$SRC
scp $FROM $SERVER:$TO

